INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES ('Livros', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES ('Eletronicos', NOW());
INSERT INTO TB_CATEGORY(NAME, CREATED_AT) VALUES ('Mesa e Banho', NOW());